name: hikki_enciclopedia
description: App for managing AnimeList functionality for iOS and Android

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  json_annotation: 4.9.0
  provider: 6.1.5
  result_type: 1.0.0
  share_plus: 11.0.0
  url_launcher: 6.3.1
  flutter_custom_tabs: 2.4.0
  async: 2.13.0
  flutter_localizations:
    sdk: flutter
  html: 0.15.6
  webview_flutter: 4.13.0
  shared_preferences: 2.5.3
  auto_route: 10.1.0+1
  freezed_annotation: 3.0.0
  dio: 5.8.0+1

  hikki_api_service:
    path: packages/hikki_api_service

  hikki_ui_kit:
    path: packages/hikki_ui_kit

  hikki_localization:
    path: packages/hikki_localization

  rxdart: 0.28.0
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  cached_network_image: 3.4.1
  app_links: 6.4.0
  lottie: 3.3.1
  flutter_dotenv: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  json_serializable: 6.9.5
  build_runner: 2.4.15
  auto_route_generator: 10.2.3
  riverpod_generator: ^2.6.5

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
