name: hikki_enciclopedia
description: App for managing AnimeList functionality for iOS and Android

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  json_annotation: 4.8.1
  provider: 6.0.5
  result_type: 0.2.0
  flutter_bloc: 8.1.3
  equatable: 2.0.0
  flutter_svg: 2.0.7
  share_plus: 7.1.0
  url_launcher: 6.1.14
  flutter_custom_tabs: 1.2.0
  async: 2.11.0
  flutter_localizations:
    sdk: flutter
  html: 0.15.4
  webview_flutter: 4.2.4
  shared_preferences: 2.2.1

  hikki_api_service:
    path: packages/hikki_api_service

  hikki_ui_kit:
    path: packages/hikki_ui_kit

  hikki_localization:
    path: packages/hikki_localization

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 6.7.1
  build_runner: 2.3.3

  flutter_lints: 2.0.3

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/shevron.svg
